---
- name: Test my_own_role from collection
  hosts: local
  gather_facts: yes
  collections:
    - my_own_namespace.yandex_cloud_elk
  roles:
    - my_own_role
  vars:
    file_path: /tmp/playbook_role_test.txt
    file_content: |
      This file was created by playbook using role
      Timestamp: {{ ansible_date_time.iso8601 }}
      From playbook: playbook_with_role_v2.yml
