namespace: my_own_namespace
name: yandex_cloud_elk
version: 3.0.0
readme: README.md
authors:
  - Your Name <your.email@example.com>
description: Collection for Yandex Cloud Observability stack
license:
  - GPL-3.0-or-later
tags:
  - yandex
  - cloud
  - observability
  - clickhouse
  - lighthouse
  - vector
dependencies: {}
repository: https://github.com/vegorshkov/ansible-dz06
documentation: https://github.com/vegorshkov/ansible-dz06
homepage: https://github.com/vegorshkov/ansible-dz06
issues: https://github.com/vegorshkov/ansible-dz06/issues
