---
- name: Create file using my_own_module
  my_own_namespace.yandex_cloud_elk.my_own_module:
    path: "{{ file_path }}"
    content: "{{ file_content }}"
  register: module_result

- name: Debug module output
  debug:
    var: module_result
